### ISSUE TITLE
No variable with name "reference' in Debugger when watching variable

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#173]
Also showing wrong type of "reference" see testString
<img width="1388" alt="screen shot 2016-03-27 at 8 51 52 pm" src="https://cloud.githubusercontent.com/assets/689092/14067168/891d55ec-f45e-11e5-8d96-6084205305e2.png">
ComponentGroupReference and ComponentReference are subclass of ReferenceBase

**Comment by VISTALL** [comment]
Already fixed with parameters

**Comment by winalex** [comment]
Not fixed. I've latest update. Doesn't like word reference :dancer:

**Comment by VISTALL** [comment]
this method contains yield ?

**Comment by winalex** [comment]
No

**Comment by VISTALL** [comment]
Idk how repeat it

**Comment by winalex** [comment]
`class SomeEvent:UnityEvent<ReferenceBase>{}
class ReferenceBase:ScriptableObject{}
class ComponentReference:ReferenceBase{}
class ComponentGroupReference:ReferenceBase{}

class MyMono:MonoBehaviour{
void Awake(){
var someEvent=new SomeEvent();
someEvent.AddListener(Handler);
someEvent.Invoke(ScriptableObject.CreateInstance<ComponentReference>());
//Scriptable Object aren't created without "new" 
}
public void Handler(ReferenceBase reference){

//Add watch
    Debug.Log(reference.GetType());
reference=ScriptableObject.CreateInstance<ComponentGroupReference>();
  Debug.Log(reference.GetType());

}
}



`

Try this!

**Comment by VISTALL** [comment]
Strange - i can't enter **Handler** method

![image](https://cloud.githubusercontent.com/assets/542934/14074715/d572f0b4-f4db-11e5-90ed-12022e1ed110.png)


when it call Invoke - no pause inside Handler

**Comment by winalex** [comment]
what Logs print?

**Comment by VISTALL** [comment]
Hm. That interest.

![image](https://cloud.githubusercontent.com/assets/542934/14074795/626cdf7a-f4dc-11e5-8663-928552393f22.png)

Why not paused. O_o

**Comment by winalex** [comment]
Put breakpoint also on someEvent.Invoke then try get in or "Play" to next breakpoint

**Comment by VISTALL** [comment]
Strange. I can't pause at any line, except *var someEvent = new SomeEvent();*

**Comment by VISTALL** [comment]
ref https://github.com/consulo/consulo-dotnet/issues/69

**Comment by winalex** [comment]
Don't close the previous issue as it is very important

**Comment by VISTALL** [comment]
if i can't reproduce - i can't fix. There no other peoples to can test - except you
